// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5iKif8w_yZqPo3QDUXpVzm6CnNtg6FEs',
    appId: '1:361684345787:web:d7b90583eb88166ef51a9e',
    messagingSenderId: '361684345787',
    projectId: 'speakdocs-1778a',
    authDomain: 'speakdocs-1778a.firebaseapp.com',
    storageBucket: 'speakdocs-1778a.firebasestorage.app',
    measurementId: 'G-Q7C02G49V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy38P7W6Sb1oQ5GVM8esgsA8iATToqyGs',
    appId: '1:361684345787:android:e7b46a4a168addd4f51a9e',
    messagingSenderId: '361684345787',
    projectId: 'speakdocs-1778a',
    storageBucket: 'speakdocs-1778a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjP-adHREl3Oyp0d8DoX9bGtn7AUo6-48',
    appId: '1:361684345787:ios:751c3fed77aac29ef51a9e',
    messagingSenderId: '361684345787',
    projectId: 'speakdocs-1778a',
    storageBucket: 'speakdocs-1778a.firebasestorage.app',
    iosBundleId: 'com.vadm.voiceAssistedDocumentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjP-adHREl3Oyp0d8DoX9bGtn7AUo6-48',
    appId: '1:361684345787:ios:751c3fed77aac29ef51a9e',
    messagingSenderId: '361684345787',
    projectId: 'speakdocs-1778a',
    storageBucket: 'speakdocs-1778a.firebasestorage.app',
    iosBundleId: 'com.vadm.voiceAssistedDocumentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5iKif8w_yZqPo3QDUXpVzm6CnNtg6FEs',
    appId: '1:361684345787:web:d40fa19412a09b3cf51a9e',
    messagingSenderId: '361684345787',
    projectId: 'speakdocs-1778a',
    authDomain: 'speakdocs-1778a.firebaseapp.com',
    storageBucket: 'speakdocs-1778a.firebasestorage.app',
    measurementId: 'G-EQXM6ZGWYG',
  );
}
